version: "3.9"
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./server/config/serviceAccountKey.json:/app/server/config/serviceAccountKey.json
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "80:5173" # map Vite's dev server to port 80 for public access
    environment:
      - VITE_PORT=80
      - VITE_API_URL=http://64.23.163.14:8080 # point to the public IP of the server
    restart: unless-stopped
