services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - ./server/config/serviceAccountKey.json:/app/server/config/serviceAccountKey.json
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - VITE_PORT=5173
      - VITE_API_URL=http://localhost:8080
